import {
  Baby,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CalendarDays,
  Calculator,
  ClipboardCheck,
  Compass,
  Dumbbell,
  Eye,
  FileText,
  FlaskConical,
  Goal,
  GraduationCap,
  Handshake,
  Heart,
  Landmark,
  Languages,
  LibraryBig,
  LockKeyhole,
  Mail,
  MapPin,
  Monitor,
  Music2,
  Newspaper,
  Palette,
  Phone,
  Presentation,
  Puzzle,
  Quote,
  School,
  Shapes,
  ShieldCheck,
  Sparkles,
  Target,
  Trees,
  Trophy,
  UserRound,
  UsersRound,
  UtensilsCrossed,
  type LucideIcon,
} from "lucide-react";

import type { ContentIcon as ContentIconName } from "@/types/content";

type ContentIconProps = {
  name: ContentIconName;
  className?: string;
};

const icons: Record<ContentIconName, LucideIcon> = {
  baby: Baby,
  "book-open": BookOpen,
  briefcase: BriefcaseBusiness,
  bus: Bus,
  calendar: CalendarDays,
  calculator: Calculator,
  "clipboard-check": ClipboardCheck,
  compass: Compass,
  dumbbell: Dumbbell,
  eye: Eye,
  "file-text": FileText,
  flask: FlaskConical,
  goal: Goal,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  heart: Heart,
  landmark: Landmark,
  languages: Languages,
  library: LibraryBig,
  "lock-keyhole": LockKeyhole,
  mail: Mail,
  "map-pin": MapPin,
  monitor: Monitor,
  music: Music2,
  newspaper: Newspaper,
  palette: Palette,
  phone: Phone,
  presentation: Presentation,
  puzzle: Puzzle,
  quote: Quote,
  school: School,
  shapes: Shapes,
  "shield-check": ShieldCheck,
  sparkles: Sparkles,
  target: Target,
  trees: Trees,
  trophy: Trophy,
  "user-round": UserRound,
  users: UsersRound,
  utensils: UtensilsCrossed,
};

export function ContentIcon({ name, className }: ContentIconProps) {
  const Icon = icons[name];

  return <Icon aria-hidden="true" className={className} strokeWidth={1.8} />;
}
